In [1]:
# Dependencies
import pandas as pd
import numpy as np
import os
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

In [2]:
# Reading csv files
data08 = pd.read_csv('Resources/Forbes Global 2000 - 2008.csv')
data09 = pd.read_csv('Resources/Forbes Global 2000 - 2009.csv')
data10 = pd.read_csv('Resources/Forbes Global 2000 - 2010.csv')
data11 = pd.read_csv('Resources/Forbes Global 2000 - 2011.csv')
data12 = pd.read_csv('Resources/Forbes Global 2000 - 2012.csv')
data13 = pd.read_csv('Resources/Forbes Global 2000 - 2013.csv')
data14 = pd.read_csv('Resources/Forbes Global 2000 - 2014.csv')
data15 = pd.read_csv('Resources/Forbes Global 2000 - 2015.csv')
data16 = pd.read_csv('Resources/Forbes Global 2000 - 2016.csv')
data17 = pd.read_csv('Resources/Forbes Global 2000 - 2017.csv')
data18 = pd.read_csv('Resources/Forbes Global 2000 - 2018.csv', error_bad_lines=False)
data19 = pd.read_csv('Resources/Forbes Global 2000 - 2019.csv')
data20 = pd.read_csv('Resources/Forbes Global 2000 - 2020.csv')
data21 = pd.read_csv('Resources/Forbes Global 2000 - 2021.csv')

In [3]:
# Removing $ from the values
data20["Sales"] = data20["Sales"].str.replace('$','')
data20["Profits"] = data20["Profits"].str.replace('$','')
data20["Assets"] = data20["Assets"].str.replace('$','')
data20["Market Value"] = data20["Market Value"].str.replace('$','')

In [4]:
# Convert M values to B and removing the characters
value = {'M':"*0.001",'B':'',',':''}
data20['Sales']= data20['Sales'].replace(value,regex=True).map(pd.eval)
data20['Sales'] = round(data20['Sales'],2)
data20['Profits']= data20['Profits'].replace(value,regex=True).map(pd.eval)
data20['Profits'] = round(data20['Profits'],2)
data20['Assets']= data20['Assets'].replace(value,regex=True).map(pd.eval)
data20['Assets'] = round(data20['Assets'],2)
data20['Market Value']= data20['Market Value'].replace(value,regex=True).map(pd.eval)
data20['Market Value'] = round(data20['Market Value'],2)

In [5]:
# checking data21 - missing industry 
data21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          2000 non-null   int64
 1   Name          2000 non-null   object
 2   Country       2000 non-null   object
 3   Sales         2000 non-null   object
 4   Profit        2000 non-null   object
 5   Assets        1999 non-null   object
 6   Market Value  2000 non-null   object
 7   Year          2000 non-null   int64
dtypes: int64(2), object(6)
memory usage: 125.1+ KB

In [6]:
# getting column names for data21
data21.columns

Index(['Rank', 'Name', 'Country', 'Sales', 'Profit', 'Assets', 'Market Value',
       'Year'],
      dtype='object')

In [7]:
# renaming columns for data21
data21.columns = ['Rank', 'Company', 'Country', 'Sales', 'Profits', 'Assets', 'Market Value',
       'Year']

In [8]:
# Removing $ from the values
data21["Sales"] = data21["Sales"].str.replace('$','')
data21["Profits"] = data21["Profits"].str.replace('$','')
data21["Assets"] = data21["Assets"].str.replace('$','')
data21["Market Value"] = data21["Market Value"].str.replace('$','')

In [9]:
# Replaced one NaN value with 0 to allow for formatting
data21 = data21.fillna(0)

In [10]:
# merging data21 with data20 to get industry column
data21_corrected = pd.merge(data21, data20, on="Company", how="left")
data21_corrected.head()

,Rank_x,Company,Country,Sales_x,Profits_x,Assets_x,Market Value_x,Year_x,Rank_y,Country/Territory,Sales_y,Profits_y,Assets_y,Market Value_y,Sector,Industry,Year_y
0,1,ICBC,China,190.5 B,45.8 B,"4,914.7 B",249.5 B,2021,1.0,China,177.2,45.3,4322.5,242.3,Financials,Major Banks,2020.0
1,2,JPMorgan Chase,United States,136.2 B,40.4 B,"3,689.3 B",464.8 B,2021,3.0,United States,142.9,30.0,3139.4,291.7,Financials,Major Banks,2020.0
2,3,Berkshire Hathaway,United States,245.5 B,42.5 B,873.7 B,624.4 B,2021,4.0,United States,254.6,81.4,817.7,455.4,Financials,Investment Services,2020.0
3,4,China Construction Bank,China,173.5 B,39.3 B,"4,301.7 B",210.4 B,2021,2.0,China,162.1,38.9,3822.0,203.8,Financials,Major Banks,2020.0
4,5,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,229.7 B,49.3 B,510.3 B,"1,897.2 B",2021,5.0,Saudi Arabia,329.8,88.2,398.3,1684.8,Energy,Oil & Gas,2020.0

In [11]:
# grabbing the desired columns for new data21
data21_corrected = data21_corrected[['Rank_x', 'Company', 'Country', 'Sales_x', 'Profits_x', 'Assets_x',
       'Market Value_x', 'Year_x', 'Sector', 'Industry']]

In [12]:
# renaming columns for data21
data21_corrected.columns = ['Rank', 'Company', 'Country', 'Sales', 'Profits', 'Assets',
       'Market Value', 'Year', 'Sector', 'Industry']

In [13]:
# reassigning corrected data21 back to data21
data21 = data21_corrected

In [14]:
# Convert M values to B and removing the characters
value = {'M':"*0.001",'B':'',',':''}
data21['Sales']= data21['Sales'].replace(value,regex=True).map(pd.eval)
data21['Sales'] = round(data21['Sales'],2) # necessary?
data21['Profits']= data21['Profits'].replace(value,regex=True).map(pd.eval)
data21['Profits'] = round(data21['Profits'],2) # necessary?
data21['Assets']= data21['Assets'].replace(value,regex=True).map(pd.eval)
data21['Assets'] = round(data21['Assets'],2) # necessary?
data21['Market Value']= data21['Market Value'].replace(value,regex=True).map(pd.eval)
data21['Market Value'] = round(data21['Market Value'],2) # necessary?

In [15]:
# Changing 0 back to NaN value in case needed
data21.replace(0,np.nan, inplace=True)

In [16]:
# rename the columns for concat
data08.columns = ['Company', 'Industry', 'Country', 'Market Value',
       'Profits', 'Assets', 'Sales', 'Rank', 'Year']
data09.columns = ['Company', 'Industry', 'Country', 'Market Value', 'Profits', 'Assets',
       'Sales', 'Rank', 'Year']
data10.columns = ['Company', 'Industry', 'Country', 'Market Value', 'Sales', 'Profits',
       'Assets', 'Rank', 'Year']
data11.columns = ['Company', 'Industry', 'Country', 'Market Value', 'Sales', 'Profits',
       'Assets', 'Rank', 'Year']
data15.columns = ['Company', 'Market Value', 'Sales', 'Profits', 'Assets', 'Rank', 'Sector',
       'Industry', 'Continent', 'Country', 'Year']
data16.columns = ['Company', 'Market Value', 'Sales', 'Profits', 'Assets', 'Rank', 'Sector',
       'Industry', 'Continent', 'Country', 'Year']
data17.columns = ['Company', 'Market Value', 'Sales', 'Profits', 'Assets', 'Rank', 'Sector',
       'Industry', 'Continent', 'Country', 'Year']
data18.columns = ['Company', 'Market Value', 'Sales', 'Profits', 'Assets', 'Rank', 'Sector',
       'Industry', 'Continent', 'Country', 'Year']
data19.columns = ['Company', 'Market Value', 'Sales', 'Profits', 'Assets', 'Rank', 'Sector',
       'Industry', 'Continent', 'Country', 'Year']
data20.columns = ['Rank', 'Company', 'Country', 'Sales', 'Profits', 'Assets',
       'Market Value', 'Sector', 'Industry', 'Year']

In [17]:
#combine the dataset together 
frames = [data08, data09, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21]

result = pd.concat(frames)

In [18]:
# Displaying new df
result

,Company,Industry,Country,Market Value,Profits,Assets,Sales,Rank,Year,Sector,Continent
0,HSBC Holdings,Banking,United Kingdom,180.81,19.13,2348.98,146.50,1.0,2008,NaN,NaN
1,General Electric,Conglomerates,United States,330.93,22.21,795.34,172.74,2.0,2008,NaN,NaN
2,Bank of America,Banking,United States,176.53,14.98,1715.75,119.19,3.0,2008,NaN,NaN
3,JPMorgan Chase,Banking,United States,136.88,15.37,1562.15,116.35,4.0,2008,NaN,NaN
4,ExxonMobil,Oil & Gas Operations,United States,465.51,40.61,242.08,358.60,5.0,2008,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1995,JTEKT,Auto & Truck Parts,Japan,3.50,-0.03,25.00,13.10,1996.0,2021,Consumer Discretionary,NaN
1996,Insurance Australia Group,Property & Casualty Insurance,Australia,9.30,-0.21,7.10,5.40,1997.0,2021,Financials,NaN
1997,Sumec Corporation,NaN,China,1.30,0.08,7.50,13.00,1997.0,2021,NaN,NaN
1998,Gold Fields,NaN,South Africa,8.90,0.72,2.60,3.90,1999.0,2021,NaN,NaN
1999,Paycom,NaN,United States,24.00,0.14,NaN,0.84,1999.0,2021,NaN,NaN

In [19]:
# find US data
us = result.loc[result["Country"] == "United States"]

In [20]:
# Removing columns
us.drop(columns=['Sector','Continent'], inplace=True)

In [21]:
# checking info on us df
us.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7882 entries, 1 to 1999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       7882 non-null   object
 1   Industry      7600 non-null   object
 2   Country       7882 non-null   object
 3   Market Value  7882 non-null   float64
 4   Profits       7875 non-null   float64
 5   Assets        7881 non-null   float64
 6   Sales         7880 non-null   float64
 7   Rank          7882 non-null   float64
 8   Year          7882 non-null   int64
dtypes: float64(5), int64(1), object(3)
memory usage: 615.8+ KB

In [22]:
# dropping null values
us.dropna(inplace = True)

In [23]:
# checking null values were successfully removed
us.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7591 entries, 1 to 1930
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       7591 non-null   object
 1   Industry      7591 non-null   object
 2   Country       7591 non-null   object
 3   Market Value  7591 non-null   float64
 4   Profits       7591 non-null   float64
 5   Assets        7591 non-null   float64
 6   Sales         7591 non-null   float64
 7   Rank          7591 non-null   float64
 8   Year          7591 non-null   int64
dtypes: float64(5), int64(1), object(3)
memory usage: 593.0+ KB

In [24]:
# create another df for correlation
us2 = us
us2 = us2.drop(columns = ['Rank', 'Year',])
us2

,Company,Industry,Country,Market Value,Profits,Assets,Sales
1,General Electric,Conglomerates,United States,330.93,22.21,795.34,172.74
2,Bank of America,Banking,United States,176.53,14.98,1715.75,119.19
3,JPMorgan Chase,Banking,United States,136.88,15.37,1562.15,116.35
4,ExxonMobil,Oil & Gas Operations,United States,465.51,40.61,242.08,358.60
9,Berkshire Hathaway,Diversified Financials,United States,216.65,13.21,273.16,118.25
...,...,...,...,...,...,...,...
1892,Fluor,Construction Services,United States,3.20,-0.44,7.30,15.70
1897,Toll Brothers,Construction Services,United States,7.50,0.49,10.90,7.30
1901,Tenneco,Auto & Truck Parts,United States,0.94,-1.50,11.90,15.40
1912,PBF Energy,Oil & Gas Operations,United States,1.70,-1.40,10.50,15.10
1930,Wintrust Financial,Regional Banks,United States,4.50,0.29,45.10,1.90

In [25]:
# correlation matrix and find the strongest positive and negative correlations for us. 
us_corr = us2.corr()
display(us_corr)

              Market Value   Profits    Assets     Sales
Market Value      1.000000  0.676520  0.236755  0.562013
Profits           0.676520  1.000000  0.335688  0.533418
Assets            0.236755  0.335688  1.000000  0.354140
Sales             0.562013  0.533418  0.354140  1.000000

In [26]:
# plot profit YOY
indicators = ["Profits","Sales","Assets"]

for indicator in indicators: 
    plt.bar(us["Year"], us[indicator], linewidth=1, color=(us[indicator] > 0).map({True: 'g', False: 'r'}))
    plt.title(f"Overall {indicator} YoY across Industries")
    plt.xlabel("Years")
    plt.ylabel(f"{indicator}") 
    plt.savefig(f"Output/overall_{indicator}_yoy.png", bbox_inches='tight')
    plt.show()

KeyboardInterrupt:

In [ ]:
# find the mean of each year
mean_val = us.groupby("Year").mean()
mean_val

In [ ]:
mean_val2 = mean_val
mean_val_corr = mean_val2.corr()
display(mean_val_corr)

In [ ]:
# Debating to remove or keep

# plot market value vs Sales
fig, ax = plt.subplots()
bar1 = plt.bar(mean_val.index, mean_val["Assets"], linewidth=1)
plt.bar_label(bar1, fmt = "%.0f", padding = 2)


plt.plot(mean_val.index,mean_val["Sales"], marker="o", color="red", linewidth=1)
for x,y in zip(mean_val.index, mean_val["Sales"]):
    label = "{:.0f}".format(y)
    plt.annotate(label, (x, y), textcoords = "offset points" , xytext = (0, 5), ha = "center")


plt.ylim(top = max(mean_val["Assets"]) + 10)
plt.xticks([x for x in mean_val.index], rotation = 45)
plt.title("Average Assets vs Sales YOY")
plt.xlabel("Year")
plt.legend(['Sales','Assets'], loc="upper left")
plt.savefig("Output/average_assets_vs_sales_yoy.png", bbox_inches='tight')
plt.show()

In [ ]:
# plot market value vs Assets
fig, ax = plt.subplots()
bar2 = plt.bar(mean_val.index, mean_val["Market Value"], linewidth=1)
plt.bar_label(bar2, fmt = "%.0f")
plt.xlim(min(mean_val.index)-.5, 2021+.5)
plt.xticks([x for x in mean_val.index], rotation = 45)

plt.plot(mean_val.index,mean_val["Assets"], marker="o", color="red", linewidth=1)
for x,y in zip(mean_val.index, mean_val["Assets"]):
    label = "{:.0f}".format(y)
    plt.annotate(label, (x, y), textcoords = "offset points" , xytext = (0, 5), ha = "center")
plt.title("Average Market Value vs Assets YOY")
plt.xlabel("Year")
plt.ylim(top = max(mean_val["Assets"]) + 10)
plt.legend([ "Assets", 'Market Value'], loc="upper left")
plt.savefig("Output/average__market_value_vs_assets_yoy.png", bbox_inches='tight')
plt.show()

Correlation between Market Value and Assets There is a strong correlation between market value and assets (0.97). Also showing on the above combo chart that market value grow as assets go up. Market value declined on 2009 then assets declined. After the housing crises, both market value and assets are trending upward.

In [ ]:
List_years_desired = [2008,2009,2020,2021]
indicators = ["Profits","Sales","Assets"]

for year in List_years_desired:
    ##Look for dataset year
    x = us.loc[us["Year"] == year]
    groupbyind = x.groupby(["Industry"])
    
    ##Groupby new dataset
    x_industry = x.groupby(["Industry"])
    print("---------------------")
    print(f"{year} graph")
    print("---------------------")
    
    for indicator in indicators:
        mean_ind_sales = groupbyind[indicator].mean()
        y = pd.DataFrame(mean_ind_sales)
    
        # sort by Sales
        y.sort_values(by=[indicator], ascending=False, inplace=True)

        # find the top 5
        top5_y = y.head()
        top5_y

        # plot top 5
        fig, ax = plt.subplots()
        bartop = plt.bar(top5_y.index, top5_y[indicator], linewidth=1, color = "green")
        plt.bar_label(bartop, fmt = "%.1f")
        plt.xticks(rotation=45)
        plt.title(f"Top 5 Average {indicator} Industry in {year}")
        plt.xlabel("Industry")
        plt.ylabel(f"{indicator}")
        plt.savefig(f"Output/Top5_Average_{indicator}_Industry_{year}.png", bbox_inches='tight')
        plt.show() 

        # find the bottom5
        bottom5_y = y.tail()
        bottom5_y

        # plot bottom 5
        fig, ax = plt.subplots()
        barbottom = plt.bar(bottom5_y.index, bottom5_y[indicator], linewidth=1, color=(bottom5_y[indicator] > 0).map({True:'g' , False: 'r'}))
        plt.bar_label(barbottom, fmt = "%.1f")
        plt.xticks(rotation=45)
        plt.title(f"Bottom 5 Average {indicator} Industry in {year}")
        plt.xlabel("Industry")
        plt.ylabel(f"{indicator}")
        plt.savefig(f"Output/Bottom5_Average_{indicator}_Industry_{year}.png", bbox_inches='tight')
        plt.show() 

# # This chart tells us which industry still remain profitable in 2008

In [ ]:
# Identifying unique companies
companies = us["Company"].unique()

In [ ]:
# Grouping by years for companies
years = us.groupby("Year")["Company"].unique()

In [ ]:
# Identifying the unique industries
industries = us["Industry"].unique()

In [ ]:
# Assigning bin labels for profit ranges and cutting into df
profit_bins = [-100, 0, 5, 10, 100] # need to sort out size for profit amounts
labels = ["Profit Loss/No Profit", "Less than $5 bil", "Between $5-10 bil", "Above $10 bil"]
us["Profit Range"] = pd.cut(us['Profits'], profit_bins, labels=labels)
us

In [ ]:
# Grabbing the desired rows with industries in financial sector
Financials = us.loc[(us["Industry"] == "Banking") | (us["Industry"] == "Major Banks") | (us["Industry"] == "Regional Banks")
              | (us["Industry"] == "Diversified Financials") | (us["Industry"] == "Investment Services")
              | (us["Industry"] == "Consumer Financial Services") | (us["Industry"] == "Diversified Insurance") 
              | (us["Industry"] == "Insurance Brokers") | (us["Industry"] == "Life & Health Insurance")  
              | (us["Industry"] == "Property & Casualty Insurance") | (us["Industry"] == "Insurance Brokers") 
              | (us["Industry"] == "Real Estate") | (us["Industry"] == "Rental & Leasing") 
              | (us["Industry"] == "Thrifts & Mortgage Finance") | (us["Industry"] == "Rental & Leasing") 
]

Financials

In [ ]:
# Grabbing the desired rows with industries in technology sector
Tech = us.loc[(us["Industry"] == 'Software & Services') | (us["Industry"] == 'Technology Hardware & Equip') 
              | (us["Industry"] == 'Computer Services') | (us["Industry"] == 'Computer Hardware') 
              | (us["Industry"] == 'Computer Storage Devices') | (us["Industry"] == 'Computer & Electronics Retail') 
              | (us["Industry"] == 'Electronics') | (us["Industry"] == 'Consumer Electronics') 
              | (us["Industry"] == 'Telecommunications Services') | (us["Industry"] == 'Semiconductors') 
              | (us["Industry"] == 'Communications Equipment')]
Tech

In [ ]:
# Grabbing the desired rows with industries in petroleum Sector
Petroleum = us.loc[(us["Industry"] == 'Oil & Gas Operations')|(us["Industry"] == 'Oil Services & Equipment')
                |(us["Industry"] == 'Natural Gas Utilities')]
Petroleum

In [ ]:
Financials.name = "Financials"
Tech.name = "Technology"
Petroleum.name = "Petroleum"

industries=[Financials,Tech,Petroleum]
years = [2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]


def industry_analysis(x_df):
   # get the highest and lowest profits
    x_df.reset_index(inplace=True, drop=True)
    x_df_highest_profits = x_df.loc[x_df.groupby("Year")["Profits"].idxmax()]
    x_df_lowest_profits = x_df.loc[x_df.groupby("Year")["Profits"].idxmin()]

    # Using for loop to plot the profit ranges in pie and bar for all years
    for year in years:
        profit_year = x_df[x_df['Year'] == year]
        ranges = profit_year.groupby('Profit Range')['Profit Range'].count()
        plt.pie(ranges.values,labels=ranges.index.values,autopct=lambda p: '{:.1f}%'.format(round(p)) if p > 0 else '',radius=1,textprops={'fontsize': 7})
        plt.title(f"{x_df.name} Sector Profit Ranges for {year}", pad=5)
        plt.legend(bbox_to_anchor=(-0.15, .5), fontsize=8)
        plt.savefig(f"Output/{x_df.name}_pr{year}_pie.png", bbox_inches='tight')
        plt.show()
        ranges.plot.bar()
        plt.xticks(rotation=45, ha='center')
        plt.ylabel('Number of Companies')
        plt.xlabel('Profit Range')
        plt.savefig(f"Output/{x_df.name}_pr{year}_bar.png", bbox_inches='tight')
        plt.show()    
        info = profit_year.aggregate({'Profits':["mean", "median", "var", "std", "sem", "min", "max"]})    
        print(ranges)
        print(info)
    
def profit_ranges(x_df):
    
    # Creating empty lists for line plot of profit ranges
    loss = []
    less = []
    between = []
    above = []
    
    for year in years:
        profits = x_df[x_df['Year'] == year]
        range = profits.groupby('Profit Range')['Profit Range'].count()
        loss.append(range.iloc[0])
        less.append(range.iloc[1])
        between.append(range.iloc[2])
        above.append(range.iloc[3])

    # Multiline plot for profit ranges 
    plt.plot(years, loss, label = 'Profit Loss/No Profit', linestyle = '-')
    plt.plot(years, less, label = 'Less than $5 billion', linestyle = '--')
    plt.plot(years, between, label = 'Between $5-10 billion', linestyle = 'dotted')
    plt.plot(years, above, label = 'Above $10 billion', linestyle = 'dashdot')
    plt.xticks()
    plt.ylabel('Number of Companies')
    plt.xlabel('Year')
    plt.title(f'{x_df.name} Sector Profit Ranges Over the Years')
    plt.savefig(f"Output/{x_df.name}_Sector_Profit _yoy.png")
    plt.legend(bbox_to_anchor=(-0.15, .5), fontsize=8)
    plt.show()
    
def profit_min_max(x_df):
    
    # Finding the profit min from all years
    highest_profits = x_df.loc[x_df.groupby("Year")["Profits"].idxmax()]
    highest_profits
    lowest_profits = x_df.loc[x_df.groupby("Year")["Profits"].idxmin()]
    lowest_profits
    
    # Assigning variables for x and y values
    year1 = highest_profits['Year']
    highs = highest_profits['Profits']
    year2 = lowest_profits['Year']
    lows = lowest_profits['Profits']
    
    # Plotting multiline for the min and max of profits over the years
    plt.plot(year1, highs, label = 'Highest Profit', linestyle = '-')
    plt.plot(year2, lows, label = 'Lowest Profit', linestyle = '--')
    plt.ylabel('Profits (billions)')
    plt.xlabel('Year')
    plt.xticks([x for x in year1], rotation=45)
    plt.title(f'{x_df.name} Highest and Lowest Profits over the Years')
    plt.legend(bbox_to_anchor=(-0.15, .5), fontsize=8)
    plt.savefig(f"Output/{x_df.name}_pr_high_low.png",  bbox_inches='tight')
    plt.show()

In [ ]:
for x in industries:
    industry_analysis(x)
    profit_ranges(x)
    profit_min_max(x)

The above plots show that during the 2008 Housing Crisis, there weren't any companies in the financial sector that made over 5 billion and the percentage of companies that experienced no profit or a profit loss doubled in 2009.  While in 2020, during the Covid19 Pandemic, it shows a decrease in companies with less than $5 billion in profit and an increase for companies that made more than 5 billion.  It appears that the 2008 Housing Crisis had a negative impact on the financial sector, while the Covid19 Pandemic had a positive impact.

The above plots show that during the 2008 Housing Crisis, the technology sector did not have a significant impact.  Although more companies showed a profit loss, there was also an increase in companies that made over 5 billion.  While in 2020, during the Covid19 Pandemic, it shows only a few companies with profit loss and more companies with over 5 billion in profit.  The maximum profit for technology also mostly increased over the years and the minimum profit mostly decreased over the years.  It appears that neither the 2008 Housing Crisis or Covid19 Pandemic, impacted the technology sector much.

In the above plots for the petroleum sector, it shows that companies experienced a decrease in profit during the 2008 Housing Crisis, particularly in years 2009 and 2010. During the Covid19 Pandemic, it also shows that companies experienced a decrease in profit.

The profit min and max multiline plot shows a steep decline in a comparison of the financial sector's maximum and minimum profits for 2009, while there was a jump in maximum and minimum profits in 2020.  It appears the financial sector was negatively impacted by the 2008 Housing Crisis and positively impacted by the Covid19 Pandemic. Further research of any other contributing factors needed to determine if the positive impact was only due to the pandemic.

The profit min and max multiline plot shows an increase in a comparison of the technology sector's maximum and minimum profits for 2009 and an increase in maximum and minimum profits in 2020. It appears that neither crisis impacted the technology sector and over the years, the sector experienced continuous increase. Further research of any other contributing factors needed to determine if the increase was solely due to the 2008 Housing Crisis or Covid19 pandemic.

The profit min and max multiline plot shows that in a comparison of the petroleum sector's maximum and minimum profits for 2009, there was a jump in maximum and decrease in minimum profits.  While in 2020, the maximum and minimum profits both decreased. It appears the petroleum sector was not negatively significantly impacted by the 2008 Housing Crisis and negatively impacted by the Covid19 Pandemic. Further research of any other contributing factors needed to determine if the negative impact was solely due to the pandemic.

In [ ]:
# Analyze sales data in financial sector, technology sector and petroleum sector
# (Create new dataframes for financials and tech to prevent conflict for further use.)
Finance = Financials
Tech = Tech
Petroleum = Petroleum

# Create a column 'Sector' for each dataframe
Finance["Sector"] = "Finance"
Tech["Sector"] = "Tech"
Petroleum["Sector"] = "Petroleum"

In [ ]:
# Average sales of each sector for all years
average_sales_finance = Finance.groupby(["Year"])["Sales"].mean()
average_sales_tech = Tech.groupby(["Year"])["Sales"].mean()
average_sales_petroleum = Petroleum.groupby(["Year"])["Sales"].mean()

# Create a dataframe of the average sales in these three sector
average_sales = pd.DataFrame({"Finance Average Sales":average_sales_finance,
                              "Technology Average Sales":average_sales_tech,
                              "Petroleum Average Sales":average_sales_petroleum})
average_sales

In [ ]:
# Plotting multiple lines graph
plt.plot(years, average_sales_finance, marker="s", color="Red", linewidth=1, label="Finance" )
plt.plot(years, average_sales_tech, marker="+", color="blue", linewidth=1, label="Technology" )
plt.plot(years, average_sales_petroleum, marker="^", color="orange", linewidth=1, label="Petroleum" )
plt.xticks([x for x in Tech["Year"].unique()], rotation = 45)
plt.ylabel('Average Sales of the sector')
plt.xlabel('Year')
plt.title('Average Sales Over the Years')
plt.legend(bbox_to_anchor=(-0.15, .5), fontsize=8)
plt.savefig("Output/three_sector_average_sales_over_the_years.png", bbox_inches='tight')
plt.show()

This multiple lines plot shows that the average sales in financial sector slowly increased from 2008 to 2021. It slowly recovered from the negative impact of 2008 Housing Crisis. The line of tech shows that the technology sector was fast growing in these year, especially after 2016. It also indicates the fact of into the information age. In petroleum sector, average sales surged to a high in 2009 since investors pouring money into crude markets as a hedge against inflation. 2017 was another volatile year for oil markets. The average sales in petroleum sector was least stable.

In [ ]:
# Find highest sales for all years in financial sector
finance_highest_sales = Finance.loc[Finance.groupby("Year")["Sales"].idxmax()]
finance_highest_sales

In [ ]:
# Find highest sales for all years in technology sector
Tech_highest_sales = Tech.loc[Tech.groupby("Year")["Sales"].idxmax()]
Tech_highest_sales

In [ ]:
# Find highest sales for all years in petroleum sector
petroleum_highest_sales = Petroleum.loc[Petroleum.groupby("Year")["Sales"].idxmax()]
petroleum_highest_sales

The max sales dataframes in financial, technology and petroleum sector shows that the companies in technology sector had max sales in these years all gained positive profit in these years. However, there were max sales companies in financials and petroleum sector had profit loss or no profit.

In [ ]:
# Find lowest sales for all years in financial sector
finance_lowest_sales = Finance.loc[Finance.groupby("Year")["Sales"].idxmin()]
finance_lowest_sales

In [ ]:
# Find lowest sales for all years in technology sector
Tech_lowest_sales = Tech.loc[Tech.groupby("Year")["Sales"].idxmin()]
Tech_lowest_sales

In [ ]:
# Find lowest sales for all years in petroleum sector
petroleum_lowest_sales = Petroleum.loc[Petroleum.groupby("Year")["Sales"].idxmin()]
petroleum_lowest_sales

The companies with lowest sales in petroleum sector did not have profit loss or no profit in these years.